plugins {
	alias(libs.plugins.spring.boot)
	alias(libs.plugins.spring.dependency.management)
	alias(libs.plugins.spring.javaformat)
}

dependencies {
	implementation libs.spring.boot.starter.web
	implementation libs.feign.core
	implementation libs.feign.hc5
	implementation libs.feign.okhttp
	implementation libs.feign.jackson

	testImplementation libs.spring.boot.starter.test
	testImplementation libs.spring.boot.resttestclient
	testRuntimeOnly libs.junit.platform.launcher
}
