plugins {
	alias(libs.plugins.spring.boot) apply false
	alias(libs.plugins.spring.dependency.management) apply false
	alias(libs.plugins.spring.javaformat) apply false
}

subprojects {
	apply plugin: 'java'
	apply plugin: 'checkstyle'
	apply plugin: 'io.spring.javaformat'

	group = 'com.eottabom'
	version = '0.0.1-SNAPSHOT'

	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(25)
		}
	}

	repositories {
		mavenCentral()
	}

	checkstyle {
		toolVersion = libs.versions.checkstyle.get()
		configFile = rootProject.file('config/checkstyle/checkstyle.xml')
	}

	dependencies {
		checkstyle libs.spring.javaformat.checkstyle
	}

	tasks.named('test') {
		useJUnitPlatform()
	}
}
