plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.eottabom'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'com.microsoft.playwright:playwright:1.54.0'

	runtimeOnly 'com.h2database:h2'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

// playwright - install Browsers
tasks.register("installBrowsers", JavaExec) {
	group = "playwright"
	description = "Installs Playwright browsers"
	classpath = sourceSets.main.runtimeClasspath
	mainClass.set("com.microsoft.playwright.CLI")
	args("install")
}

// playwright - codegen
tasks.register("codegen", JavaExec) {
	group = "playwright"
	description = "Launches playwright codegen"
	classpath = sourceSets.main.runtimeClasspath
	mainClass.set("com.microsoft.playwright.CLI")
	args("codegen", "https://the-internet.herokuapp.com/login")
}
