pluginManagement {
	repositories {
		gradlePluginPortal()
		mavenCentral()
	}
}

rootProject.name = 'let-me-code'

include 'jpa-entity'
include 'playwright'
include 'mongodb-pagination'
include 'jmh-final-keyword'
include 'jmh-logger'
include 'jmh-serialization'
include 'grpc-example'
include 'jpa-y2k38'
include 'redis-dns-cache'
include 'thread-dump'
include 'istio-ambient-demo:gateway'
include 'istio-ambient-demo:authz-server'
include 'url-encoding'
