# TO-BE: nginx(ALB) -> kubectl port-forward(:18080) -> Istio Gateway -> HTTPRoute -> external-a
server {
    listen 80;

    location = /api {
        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header Host external-a.local; # HTTPRoute.hostnames 와 매칭되어야 함
        proxy_pass http://host.docker.internal:18080;
    }
}
