DROP TABLE IF EXISTS time_test;

CREATE TABLE time_test (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ts_col TIMESTAMP NULL,
    dt_col DATETIME NULL
);

DROP TABLE IF EXISTS coupon;

CREATE TABLE coupon (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    expires_at DATETIME NOT NULL
);